[project]
name = "reverb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "matplotlib>=3.10.5",
    "nltk>=3.9.1",
    "requests>=2.32.4",
    "wordcloud>=1.9.4",
]
